#!/usr/bin/env bash
if [ $# -ne 3 ]; then
    echo $0: usage: setuppj [Github User Name] [Project Name] [Project Description]
    exit 1
fi
gname=$1
pname=$2
desc=$3
mkdir $name
cd $pname
echo "node_modules" > .gitignore
echo "# $pname\n$desc\n" > README.md
cp ../LICENSE.md LICENSE.md
cp ../tempserv.js server.js
npm init
node ../writenode.js
npm install express --save
curl -u $gname https://api.github.com/user/repos -d '{"name":"'$pname'"}'
git init
heroku create $pname
heroku git:remote -a $pname
git remote add origin https://github.com/$gname/$pname.git
git add --all
git commit -m "initial setup commit"
git push -u origin master
git push heroku master
wget -qO- https://$pname.herokuapp.com/ | echo "\n"