#!/usr/bin/env bash
if [ $# -ne 3 ]; then
    echo $0: usage: setuppj [Github User Name] [Project Name] [Project Description]
    exit 1
fi
gname=$1
pname=$2
desc=$3
#mkdir $name
#cd $pname
npm init
node ../writenode.js
echo "node_modules" > .gitignore
#echo "# $pname\n$desc\n" > README.md
cp ../LICENSE.md LICENSE.md
curl -u $gname https://api.github.com/user/repos -d '{"name":"'$pname'"}'
git init
npm install express --save
cp ../tempserv.js server.js
heroku create $pname
heroku git:remote -a $pname
git add --all
git commit -m "initial setup commit"
git remote add origin https://github.com/$gname/$pname.git
git push -u origin master
#git push heroku master
#wget -qO- https://rhpms.herokuapp.com/ | echo "\n"